### ISSUE TITLE
Error when executing postgis image

### ISSUE THREAD

**Issue by joaodubas** [testcontainers/testcontainers-elixir#106]
I configured `testcontainers` on one of my projects that uses `postgres` with the `postgis` extension enabled. When I try to execute the tests, I receive this message:

```elixir
23:10:57.225 [error] Task #PID<0.488.0> started from Testcontainers terminating
** (ArgumentError) Image postgis/postgis:16-3.4-alpine is not compatible with postgres
    (testcontainers 1.8.1) lib/container/postgres_container.ex:192: Testcontainers.ContainerBuilder.Testcontainers.PostgresContainer.build/1
    (testcontainers 1.8.1) lib/testcontainers.ex:226: Testcontainers.start_and_wait/2
    (testcontainers 1.8.1) lib/testcontainers.ex:132: anonymous fn/3 in Testcontainers.handle_call/3
    (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.16.3) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: #Function<1.102782053/0 in Testcontainers.handle_call/3>
    Args: []
```

As you can see, I'm using the image [`postgis/postgis`](https://hub.docker.com/r/postgis/postgis) on the tests. Howerver [there is a validation](https://github.com/testcontainers/testcontainers-elixir/blob/77bc2284b355f5d11945f2b895e397f71156d0d6/lib/container/postgres_container.ex#L191-L195) that prevents executing images other than the official [`postgres`](https://hub.docker.com/_/postgres).

In this case, what would be best solution:

1. Open a PR, allowing alternative images to be run
2. Implement my own container, based on [`Testcontainers.Postgrescontainer`](https://github.com/testcontainers/testcontainers-elixir/blob/main/lib/container/postgres_container.ex)

**Comment by jarlah** [comment]
I don't think there is much difference, in basic usage, between the two. So if you make a PR that either
1. Changes the validation of the postgres container to also include postgis (meh ...)
2. Make a method that disables image validation by setting a boolean field, similar to the other methods that sets config fields (maybe a good solution) 
Then I could look into it.

**Comment by joaodubas** [comment]
Thanks for the suggestions. I'm looking into the best approach to turn off the image validation with a control field.

**Comment by joaodubas** [comment]
Thanks for all the help. With the release of [1.8.3][0], I can execute the `postgis` database using the `Testcontainers.PostgresContainer` implementation. I adjusted my `application.ex` with:

```elixir
    if Application.get_env(:testcontainers, :enabled, false) do
      {:ok, _container} =
        Testcontainers.Ecto.postgres_container(
          app: :foundation,
          image: "postgis/postgis:16-3.4-alpine",
          check_image: "postgis/postgis"
        )
    end
```

[0]: https://github.com/testcontainers/testcontainers-elixir/releases/tag/v1.8.3
