### ISSUE TITLE
Consider strategies if network_mode is not supported

### ISSUE THREAD

**Issue by jarlah** [testcontainers/testcontainers-elixir#111]
Following changes from https://github.com/testcontainers/testcontainers-elixir/pull/107

Either fail container creation if network_mode is not supported, aka the host machine is macOS, or diff the the values got back from docker engine after creation and log some error message if the desired container state does not meet the actual container state

**Comment by sleipnir** [comment]
@jarlah Generally, when I need a container to access the host on MacOS or Windows, I make a direct reference to the host's IP because on these two systems, network mode host doesn't really work.

**Comment by jarlah** [comment]
@sleipnir can you look at my suggestion on how to solve it. Its not a good solution to allow it for macos or windows when its not really working out of the box. Especially when we cant test it. Maybe there is a way to test on a windows or macos host 😆 but i dont know about it. Therefore i would like this to be a linux specific feature for now, because its going to generate tons of issues when/if people start using it ...

**Comment by jarlah** [comment]
@eddumelendez you are working on the java version, how is this solved in java and the other ports? with regards to support for network mode? Im thinking asking first, getting some poiinters and maybe then read some code. My solution of rejecting network mode on non linux host systems is not good enough. I should propably only restrict the host network_mode on linux and not network_mode in general. So, basically im just toying around with this issue and the accompanying PR.

**Comment by sleipnir** [comment]
> My solution of rejecting network mode on non linux host systems is not good enough. I should propably only restrict the host network_mode on linux and not network_mode in general. So, basically im just toying around with this issue and the accompanying PR.

Hello @jarlah, good to know that I sparked your interest in this topic.
I think if Docker's behavior is not to block network_mode entirely and just leave it ineffective for host mode on other systems it should be accompanied by this library.

**Comment by jarlah** [comment]
@sleipnir in my PR i have added a warning log when used with linux and host mode when using with_network_mode. Something that triggers the user of the function to find a solution if it doesnt work, if the user reads the logs that is. So not a big change really ;) i went away from the idea of blocking the function on non-linux systems :D because it actually has beta support on docker desktop on almost all platforms

**Comment by jarlah** [comment]
basically introduced this new function 

https://github.com/testcontainers/testcontainers-elixir/pull/115/files#diff-88e48f0873a5e705262da4ac2f1fdf95573001e334f0db857677d19aa44d9f3bR190

and not running tests on non linux systems, and log the test skip, because thats os and setup dependent.
