### ISSUE TITLE
Add Testcontainers User-Agent

### ISSUE THREAD

**Issue by eddumelendez** [testcontainers/testcontainers-elixir#81]
Add the following User-Agent `tc-elixir/<version>` when making calls to Docker Engine.

Looking at the code, I think the change should be added into the options [here](https://github.com/testcontainers/testcontainers-elixir/blob/main/lib/connection/connection.ex#L20)

**Comment by jarlah** [comment]
i might need to find out how to pass headers into the docker engine library. Either update the library or use existing ways to pass in headers. To be figured out.

**Comment by jarlah** [comment]
ui think we use same technique as in #90 if it works
